variables:
  MAVEN_CLI_OPTS: "-s ./settings.xml --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  
stages:
  - build
  - test
  - deploy
  - docker

.maven-build:
  image: maven:3.8.1-openjdk-15
  stage: build
  cache:
    paths:
      - .m2/

build:
  extends: .maven-build
  script:
    - mvn $MAVEN_CLI_OPTS clean install -X
  artifacts:
    paths:
      - ./target
  when: always
  
test:
  extends: .maven-build
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

deploy:
  extends: .maven-build
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy

docker:
  extends: .maven-build
  stage: docker
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - mvn $MAVEN_CLI_OPTS push -P PUSH -Ddocker.login=$CI_REGISTRY_USER