sudo: false
language: java
jdk: openjdk13

addons:
  sonarcloud:
    organization: "collonville-tom-github"
    token: "cd3f317b2dc0418833b75ccdd44d3303c953da8b"

before_install: true
install : true
before_script : true

script:
  - cp settings.xml $HOME/.m2/settings.xml
  - mvn clean install -U
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
